<a href="https://colab.research.google.com/github/Ordaz-Yerikendy/Metodos-Numericos/blob/main/Factorizaci%C3%B3nLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np

In [31]:
def facLU(A):
    """
    Realiza la factorización LU de una matriz cuadrada A.
    La matriz A se descompone en A = L * U, donde:
    - L es una matriz triangular inferior (con 1s en la diagonal principal).
    - U es una matriz triangular superior.

    Parámetros:
    A (numpy.ndarray): Matriz cuadrada de tamaño nxn.

    Retorna:
    L (numpy.ndarray): Matriz triangular inferior.
    U (numpy.ndarray): Matriz triangular superior.
    """
    n = A.shape[0]  # Tamaño de la matriz
    L = np.eye(n)   # Inicializamos L como matriz identidad
    U = A.copy()    # Copia de A para modificarla y obtener U

    for i in range(n):
        # Verificamos si el pivote es cero para evitar división por cero
        if U[i, i] == 0:
            raise ValueError("El pivote es cero. Reordenar filas para continuar.")

        for j in range(i+1, n):
            # Calculamos el multiplicador
            factor = U[j, i] / U[i, i]
            L[j, i] = factor  # Guardamos el multiplicador en L
            # Restamos el múltiplo de la fila i de U a la fila j de U
            U[j, i:] -= factor * U[i, i:]

    return L, U

In [32]:
# Definimos la matriz de prueba
A= np.array([
    [1, 1, 0, 3],
    [2, 1, -1, 1],
    [3, -1, -1, 2],
    [-1, 2, 3, -1]
], dtype=float)

In [33]:
# Aplicamos la factorización LU
L, U = facLU(A)

In [34]:
# Verificamos el resultado
LU = np.dot(L, U)

In [35]:
# Mostramos los resultados
print("La Matriz A:")
print(A)
print("\nLa Matriz L (triangular inferior):")
print(L)
print("\nLa Matriz U (triangular superior):")
print(U)
print("\nCálculo de L * U:")
print(LU)

La Matriz A:
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]

La Matriz L (triangular inferior):
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

La Matriz U (triangular superior):
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Cálculo de L * U:
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]


In [36]:
# Comprobamos si la matriz LU es igual a la original
if np.allclose(A, LU):
    print("\nLa factorización LU es correcta.")
else:
    print("\nLa factorización LU es incorrecta.")


La factorización LU es correcta.
