<a href="https://colab.research.google.com/github/Ordaz-Yerikendy/Metodos-Numericos/blob/main/TutorialdeNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Librería numpy

**¿Qúe es la librería numpy?**

Es muy útil para realizar cálculos lógicos y matemáticos sobre cuadros y matrices. Puede realizar estas operaciones de manera mucho más rápida y eficaz que las listas de Python.

Los arreglos de NumPy tienen algunas ventajas sobre las listas tradicionales de Python. En primer lugar, utilizan menos memoria y espacio de almacenamiento, que es su principal punto fuerte.

Además, NumPy ofrece un mejor rendimiento en términos de velocidad de ejecución. Sin embargo, es más fácil y cómodo de usar.

A continuación se estarán presentando ejemplos para poder usar esta librería

In [1]:
#Primer ejemplo
import numpy as np

# Definir el tamaño de la tabla (en este caso, de 1 a 10)
n = 10

# Crear una matriz de n x n con las multiplicaciones
tabla_multiplicar = np.arange(1, n+1).reshape((n, 1)) * np.arange(1, n+1)

# Imprimir la tabla de multiplicar
print("Tabla de multiplicar:")
print(tabla_multiplicar)


Tabla de multiplicar:
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [2]:
#Segundo ejemplo
import numpy as np  # Importamos la librería numpy

# 1. Crear un arreglo con numpy
arreglo = np.array([1, 2, 3, 4, 5])
print("Arreglo original:", arreglo)

# 2. Multiplicar todos los elementos por 2
arreglo_multiplicado = arreglo * 2
print("Arreglo después de multiplicar por 2:", arreglo_multiplicado)

# 3. Calcular la media del arreglo
media = np.mean(arreglo)
print("La media del arreglo es:", media)

# 4. Crear un arreglo de ceros
arreglo_zeros = np.zeros(3)
print("Arreglo de ceros:", arreglo_zeros)

# 5. Crear un arreglo con un rango de valores
arreglo_rango = np.arange(0, 10, 2)
print("Arreglo con rango de 0 a 10, con paso 2:", arreglo_rango)


Arreglo original: [1 2 3 4 5]
Arreglo después de multiplicar por 2: [ 2  4  6  8 10]
La media del arreglo es: 3.0
Arreglo de ceros: [0. 0. 0.]
Arreglo con rango de 0 a 10, con paso 2: [0 2 4 6 8]


In [3]:
#Tercer ejemplo
import numpy as np  # Importamos la librería numpy

# 1. Crear una matriz 3x3
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz original:")
print(matriz)

# 2. Operación: Sumar 5 a cada elemento de la matriz
matriz_sumada = matriz + 5
print("\nMatriz después de sumar 5 a cada elemento:")
print(matriz_sumada)

# 3. Obtener la transpuesta de la matriz
matriz_transpuesta = np.transpose(matriz)
print("\nMatriz transpuesta:")
print(matriz_transpuesta)

# 4. Generar una matriz de números aleatorios de tamaño 3x3
matriz_random = np.random.rand(3, 3)  # Números aleatorios entre 0 y 1
print("\nMatriz de números aleatorios 3x3:")
print(matriz_random)

# 5. Filtrar los elementos de la matriz que son mayores que 4
filtro = matriz > 4  # Crea una máscara booleana
matriz_filtrada = matriz[filtro]
print("\nElementos de la matriz mayores que 4:")
print(matriz_filtrada)

# 6. Calcular la media de todos los elementos de la matriz
media_matriz = np.mean(matriz)
print("\nLa media de todos los elementos de la matriz es:", media_matriz)

# 7. Crear un arreglo con valores en un rango (de 0 a 20) con paso 3
arreglo_rango = np.arange(0, 20, 3)
print("\nArreglo con valores de 0 a 20 con paso de 3:")
print(arreglo_rango)


Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz después de sumar 5 a cada elemento:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matriz transpuesta:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Matriz de números aleatorios 3x3:
[[0.03433259 0.10393371 0.30803657]
 [0.09229134 0.31848093 0.13898528]
 [0.75857832 0.59387479 0.4327043 ]]

Elementos de la matriz mayores que 4:
[5 6 7 8 9]

La media de todos los elementos de la matriz es: 5.0

Arreglo con valores de 0 a 20 con paso de 3:
[ 0  3  6  9 12 15 18]
